### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by pema-enu** [pema-enu/MP3#1]
We have joined title with movie_link, however it is giving multiple results of the same movie (we looked at Pitch Perfect and its sequels). Instead of showing us Pitch perfect 1,2 and 3 it gives us multiple results of the same movie(with the same movie_id).

**Comment by sverma71** [comment]
I figured out how to do it. We can do multiple within the query and group by id

**Comment by pema-enu** [comment]
OMG thanks Sneha! I just saw it on the R-markdown. Looks great!
